The-Avengers-kernel/musinsa-server-v1

src/main/java/com/avengers/musinsa/global/base/BaseResponse.java
src/main/java/com/avengers/musinsa/global/exception/ExceptionAdvice.java
src/main/java/com/avengers/musinsa/global/exception/RestApiException.java
src/main/java/com/avengers/musinsa/global/exception/code/BaseCodeDto.java
src/main/java/com/avengers/musinsa/global/exception/code/BaseErrorCodeInterface.java
src/main/java/com/avengers/musinsa/global/exception/code/BaseSuccessCodeInterface.java
src/main/java/com/avengers/musinsa/global/exception/code/status/FilesErrorStatus.java
src/main/java/com/avengers/musinsa/global/exception/code/status/GlobalErrorStatus.java
src/main/java/com/avengers/musinsa/global/exception/code/status/SuccessStatus.java
src/main/java/com/avengers/musinsa/global/util/uuid/Uuid.java
src/main/java/com/avengers/musinsa/global/util/uuid/UuidRepository.java
src/main/java/com/avengers/musinsa/test/TestDto.java
src/main/java/com/avengers/musinsa/test/TestUser.java
src/main/java/com/avengers/musinsa/test/TestUserController.java
src/main/java/com/avengers/musinsa/test/TestUserDtoConverter.java

Jsp 홈 화면 만드는 것이었으나.. 즉흥적으로 응답 핸들러로 바꿈..

통일 응답 핸들러 설정

---

src/main/resources/table6-script.sql

user_id NUMBER(10) NULL, //user_id 비식별 관계 - 비회원도 조회 로그 접근 가능이므로, NULL 하용, FK 제거
CONSTRAINT PK_product_view_logs PRIMARY KEY (product_view_log_id),
- 주석 확인 부탁드립니다:)

 리뷰 및 활동 도메인 (김희재)

---

src/main/java/com/avengers/musinsa/coupons/CouponConditions.java
src/main/java/com/avengers/musinsa/coupons/CouponDiscountRules.java
src/main/java/com/avengers/musinsa/coupons/CouponTypes.java
src/main/java/com/avengers/musinsa/coupons/Coupons.java
src/main/java/com/avengers/musinsa/shipments/ProductShippingStatus.java
src/main/java/com/avengers/musinsa/shipments/Shipments.java
src/main/java/com/avengers/musinsa/shipments/ShippingFeeConditions.java
src/main/java/com/avengers/musinsa/shipments/ShippingFeePolicies.java
src/main/java/com/avengers/musinsa/shipments/ShippingFees.java
src/main/java/com/avengers/musinsa/shipments/ShippingRequestTypes.java
src/main/java/com/avengers/musinsa/shipments/ShippingStatuses.java

#15 엔티티 작성

---

src/main/java/com/avengers/musinsa/domain/brand/controller/ShowRecentBrandController.java
src/main/java/com/avengers/musinsa/domain/brand/dto/BrandDto.java
src/main/java/com/avengers/musinsa/domain/brand/repository/BrandRepository.java
src/main/java/com/avengers/musinsa/domain/brand/service/BrandService.java
src/main/java/com/avengers/musinsa/mapper/BrandMapper.java
src/main/resources/mapper/BrandMapper.xml

[희재] 최근 방문한 브랜드 조회 기능 구현

---

src/main/java/com/avengers/musinsa/domain/brand/controller/BrandController.java
src/main/java/com/avengers/musinsa/domain/brand/dto/response/BrandListResponse.java
src/main/java/com/avengers/musinsa/domain/brand/dto/response/BrandResponse.java
src/main/java/com/avengers/musinsa/domain/brand/repository/BrandRepository.java
src/main/java/com/avengers/musinsa/domain/brand/service/BrandService.java
src/main/java/com/avengers/musinsa/domain/product/dto/response/CategoryProductResponse.java
src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepository.java
src/main/java/com/avengers/musinsa/mapper/BrandMapper.java
src/main/resources/mapper/BrandMapper.xml

[조현희] 전체 브랜드 목록 조회

---

src/main/java/com/avengers/musinsa/domain/main/MainController.java
src/main/java/com/avengers/musinsa/domain/order/service/OrderService.java
src/main/resources/mapper/ProductMapper.xml

[최민영] 카테고리 상품 목록 조회 시 충돌 해결

---

src/main/java/com/avengers/musinsa/domain/brand/controller/BrandController.java
src/main/java/com/avengers/musinsa/domain/brand/dto/response/BrandByCategoryResponse.java
src/main/java/com/avengers/musinsa/domain/brand/repository/BrandRepository.java
src/main/java/com/avengers/musinsa/domain/brand/service/BrandService.java
src/main/java/com/avengers/musinsa/mapper/BrandMapper.java
src/main/resources/mapper/BrandMapper.xml

`/api/v1/categories/100/brands`
- GET /api/v1/categories/{categoryId}/brands
- 브랜드 좋아요 수 기준 정렬

[조현희] feat: 카테고리별 브랜드 목록 조회

---

src/main/java/com/avengers/musinsa/domain/product/controller/ProductController.java
src/main/java/com/avengers/musinsa/domain/product/dto/response/ProductDetailDescriptionResponse.java
src/main/java/com/avengers/musinsa/domain/product/entity/Product.java
src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepository.java
src/main/java/com/avengers/musinsa/domain/product/service/ProductService.java
src/main/java/com/avengers/musinsa/mapper/ProductMapper.java
src/main/resources/mapper/ProductMapper.xml

[김동균] feat: 상품 상세 설명 조회

---

src/main/java/com/avengers/musinsa/domain/user/controller/CartController.java
src/main/java/com/avengers/musinsa/domain/user/dto/ProductOptionInfo.java
src/main/java/com/avengers/musinsa/domain/user/dto/ProductOptionUpdateRequest.java
src/main/java/com/avengers/musinsa/domain/user/repository/CartRepository.java
src/main/java/com/avengers/musinsa/domain/user/service/CartService.java
src/main/java/com/avengers/musinsa/mapper/CartMapper.java
src/main/resources/mapper/CartMapper.xml

유저의 장바구니 - PRODUCT_ID: 1, CART_OPTION: S/black
유저가 장바구니에 담은 상품의 옵션
변경하기 - 사이즈 L로
결과

[김진용]상품 옵션 변경 기능 구현

---

src/main/java/com/avengers/musinsa/domain/brand/repository/BrandRepository.java
src/main/java/com/avengers/musinsa/domain/brand/service/BrandService.java
src/main/java/com/avengers/musinsa/mapper/BrandMapper.java
src/main/resources/mapper/BrandMapper.xml
src/main/resources/mapper/ProductMapper.xml

기능적인 로직은 그대로 두고, 메서드명만 직관적으로 바꾸었습니다.

[조현희] refactoring: 메서드명 수정

---

src/main/java/com/avengers/musinsa/domain/order/controller/OrderController.java
src/main/java/com/avengers/musinsa/domain/order/repository/OrderRepository.java
src/main/java/com/avengers/musinsa/domain/order/repository/OrderRepositoryImpl.java
src/main/java/com/avengers/musinsa/domain/order/service/OrderService.java
src/main/java/com/avengers/musinsa/domain/shipments/controller/ShippingAddressController.java
src/main/java/com/avengers/musinsa/domain/shipments/dto/ShippingAddressDTO.java
src/main/java/com/avengers/musinsa/domain/shipments/dto/ShippingAddressOrderDTO.java
src/main/java/com/avengers/musinsa/domain/shipments/repository/ShippingAddressRepository.java
src/main/java/com/avengers/musinsa/domain/shipments/service/ShippingAddressService.java
src/main/java/com/avengers/musinsa/mapper/OrderMapper.java
src/main/java/com/avengers/musinsa/mapper/ShippingAddressMapper.java
src/main/resources/mapper/OrderMapper.xml
src/main/resources/mapper/ShippingAddressMapper.xml

Feature #75 order product shipments

[박은정] 주문서 배송지 목록 조회

---

src/main/java/com/avengers/musinsa/domain/brand/controller/BrandLikeController.java
src/main/java/com/avengers/musinsa/domain/product/controller/ProductLikeController.java
src/main/java/com/avengers/musinsa/domain/product/dto/response/UserProductStatus.java
src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepository.java
src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepositoryImpl.java
src/main/java/com/avengers/musinsa/domain/product/service/ProductService.java
src/main/java/com/avengers/musinsa/domain/product/service/ProductServiceImpl.java
src/main/java/com/avengers/musinsa/mapper/ProductMapper.java
src/main/resources/mapper/BrandMapper.xml
src/main/resources/mapper/ProductMapper.xml

- 사용자가 상품을 처음 좋아요할 경우 user_product_like 테이블에 레코드 추가
- 상품 좋아요 수(products.product_likes) 증가
- 이미 좋아요한 경우 liked 값 0 ↔ 1로 토글
- 토글 시 상품 좋아요 수 동기화 (+1 / -1)
- 최종적으로 사용자의 현재 상품 좋아요 상태 반환

[조현희] 상품 좋아요 토글 기능

---

src/main/webapp/WEB-INF/views/main/header.jsp
src/main/webapp/WEB-INF/views/main/main.jsp
src/main/webapp/resources/css/header.css

[조현희] feature: header.jsp

---

src/main/webapp/WEB-INF/views/user/cart.jsp
src/main/webapp/resources/js/cart.js
src/main/webapp/resources/js/toolbar.js

[김진용] 장바구니 상품 수량 변경 안됨 오류 수정 및 결제 시 userCartId값 넘겨주도록 수정

---

src/main/webapp/resources/css/cart.css

[김진용] 이미지 css 수정

---

src/main/java/com/avengers/musinsa/config/SecurityConfig.java
src/main/java/com/avengers/musinsa/viewController/ShippingAddressViewController.java
src/main/resources/mapper/OrderMapper.xml
src/main/resources/mapper/ShippingAddressMapper.xml
src/main/webapp/WEB-INF/views/shipments/shippingAddressList.jsp

[박은정] 배송지 목록 화면 조회 /feature-#135-shipping-addresses-order

---

src/main/java/com/avengers/musinsa/domain/main/MainController.java
src/main/webapp/WEB-INF/views/product/searchProducts.jsp
src/main/webapp/resources/css/search.css

[김진용] 키워드 검색 화면 구현

---

src/main/webapp/resources/js/category.js

[조현희] fit: 상품 카테고리 - 중분류 선택 시 검색화면으로 링크이동

---

src/main/webapp/WEB-INF/views/error.jsp
src/main/webapp/WEB-INF/views/order/orderPage.jsp
src/main/webapp/WEB-INF/views/order/test.jsp
src/main/webapp/WEB-INF/views/product/cart_test.jsp
src/main/webapp/WEB-INF/views/product/productDetailPage.jsp
src/main/webapp/WEB-INF/views/shipments/shippingAddressList.jsp
src/main/webapp/WEB-INF/views/test/testindex.jsp
src/main/webapp/WEB-INF/views/test/user.jsp

[조현희] 헤더 코드 오류 해결

---

src/main/java/com/avengers/musinsa/domain/category/dto/response/CategoryProductResponse.java
src/main/java/com/avengers/musinsa/viewController/ProductViewController.java
src/main/webapp/WEB-INF/views/product/categoryProductsPage.jsp
src/main/webapp/resources/css/categoryProductsPage.css
src/main/webapp/resources/js/category.js

[김진용]카테고리 검색 결과 화면 구현

---

src/main/webapp/WEB-INF/views/product/categoryProductsPage.jsp
src/main/webapp/WEB-INF/views/product/searchProducts.jsp
src/main/webapp/resources/css/categoryProductsPage.css
src/main/webapp/resources/css/search.css

[김진용] 카테고리 상품 목록, 키워드 검색 상품 목록 리뷰 평점과 개수 나오도록 수정

---

src/main/java/com/avengers/musinsa/domain/product/controller/ProductController.java
src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepository.java
src/main/java/com/avengers/musinsa/domain/product/repository/ProductRepositoryImpl.java
src/main/java/com/avengers/musinsa/domain/product/service/ProductService.java
src/main/java/com/avengers/musinsa/domain/product/service/ProductServiceImpl.java
src/main/java/com/avengers/musinsa/mapper/ProductMapper.java
src/main/java/com/avengers/musinsa/viewController/ProductViewController.java
src/main/resources/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/product/categoryProductsPage.jsp
src/main/webapp/WEB-INF/views/product/searchProducts.jsp
src/main/webapp/resources/css/categoryProductsPage.css
src/main/webapp/resources/css/search.css

상품 카테고리 상품 조회시, 검색 시 상품 목록 필터링 기능 구현하였습니다.
인기순/ 가격 높은 순/ 가격 낮은 순

[조현희] 상품 목록 조회 필터링 화면 구현

---

src/main/webapp/resources/css/category.css
src/main/webapp/resources/css/search.css

[조현희] fix: 브랜드 이미지 크기 조정 및 흑백 반전 적용

---

src/main/java/com/avengers/musinsa/domain/shipments/controller/ShippingAddressController.java
src/main/java/com/avengers/musinsa/domain/shipments/dto/ShippingAddressCreateDTO.java
src/main/java/com/avengers/musinsa/domain/shipments/repository/ShippingAddressRepository.java
src/main/java/com/avengers/musinsa/domain/shipments/service/ShippingAddressService.java
src/main/java/com/avengers/musinsa/mapper/ShippingAddressMapper.java
src/main/java/com/avengers/musinsa/viewController/ShippingAddressViewController.java
src/main/resources/mapper/ShippingAddressMapper.xml
src/main/webapp/WEB-INF/views/shipments/shippingAddressEditForm.jsp
src/main/webapp/WEB-INF/views/shipments/shippingAddressForm.jsp
src/main/webapp/WEB-INF/views/shipments/shippingAddressList.jsp

배송지 추가 (완료)
배송지 수정 (완료)
배송지 추가/수정에서 주소찾기 카카오/다음 연동완료
기본배송지 변경(완료)
배송지 삭제 (완료)

[박은정] 배송지 추가, 수정,삭제 구현 Feature #184 shippingaddress
